<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Joseph Luchman" />

<meta name="date" content="2022-02-19" />

<title>Conceptual Introduction to Dominance Analysis</title>

<script src="data:application/javascript;base64,Ly8gUGFuZG9jIDIuOSBhZGRzIGF0dHJpYnV0ZXMgb24gYm90aCBoZWFkZXIgYW5kIGRpdi4gV2UgcmVtb3ZlIHRoZSBmb3JtZXIgKHRvCi8vIGJlIGNvbXBhdGlibGUgd2l0aCB0aGUgYmVoYXZpb3Igb2YgUGFuZG9jIDwgMi44KS4KZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignRE9NQ29udGVudExvYWRlZCcsIGZ1bmN0aW9uKGUpIHsKICB2YXIgaHMgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yQWxsKCJkaXYuc2VjdGlvbltjbGFzcyo9J2xldmVsJ10gPiA6Zmlyc3QtY2hpbGQiKTsKICB2YXIgaSwgaCwgYTsKICBmb3IgKGkgPSAwOyBpIDwgaHMubGVuZ3RoOyBpKyspIHsKICAgIGggPSBoc1tpXTsKICAgIGlmICghL15oWzEtNl0kL2kudGVzdChoLnRhZ05hbWUpKSBjb250aW51ZTsgIC8vIGl0IHNob3VsZCBiZSBhIGhlYWRlciBoMS1oNgogICAgYSA9IGguYXR0cmlidXRlczsKICAgIHdoaWxlIChhLmxlbmd0aCA+IDApIGgucmVtb3ZlQXR0cmlidXRlKGFbMF0ubmFtZSk7CiAgfQp9KTsK"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="data:text/css,body%20%7B%0Abackground%2Dcolor%3A%20%23fff%3B%0Amargin%3A%201em%20auto%3B%0Amax%2Dwidth%3A%20700px%3B%0Aoverflow%3A%20visible%3B%0Apadding%2Dleft%3A%202em%3B%0Apadding%2Dright%3A%202em%3B%0Afont%2Dfamily%3A%20%22Open%20Sans%22%2C%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20Arial%2C%20sans%2Dserif%3B%0Afont%2Dsize%3A%2014px%3B%0Aline%2Dheight%3A%201%2E35%3B%0A%7D%0A%23TOC%20%7B%0Aclear%3A%20both%3B%0Amargin%3A%200%200%2010px%2010px%3B%0Apadding%3A%204px%3B%0Awidth%3A%20400px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Aborder%2Dradius%3A%205px%3B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Afont%2Dsize%3A%2013px%3B%0Aline%2Dheight%3A%201%2E3%3B%0A%7D%0A%23TOC%20%2Etoctitle%20%7B%0Afont%2Dweight%3A%20bold%3B%0Afont%2Dsize%3A%2015px%3B%0Amargin%2Dleft%3A%205px%3B%0A%7D%0A%23TOC%20ul%20%7B%0Apadding%2Dleft%3A%2040px%3B%0Amargin%2Dleft%3A%20%2D1%2E5em%3B%0Amargin%2Dtop%3A%205px%3B%0Amargin%2Dbottom%3A%205px%3B%0A%7D%0A%23TOC%20ul%20ul%20%7B%0Amargin%2Dleft%3A%20%2D2em%3B%0A%7D%0A%23TOC%20li%20%7B%0Aline%2Dheight%3A%2016px%3B%0A%7D%0Atable%20%7B%0Amargin%3A%201em%20auto%3B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dcolor%3A%20%23DDDDDD%3B%0Aborder%2Dstyle%3A%20outset%3B%0Aborder%2Dcollapse%3A%20collapse%3B%0A%7D%0Atable%20th%20%7B%0Aborder%2Dwidth%3A%202px%3B%0Apadding%3A%205px%3B%0Aborder%2Dstyle%3A%20inset%3B%0A%7D%0Atable%20td%20%7B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dstyle%3A%20inset%3B%0Aline%2Dheight%3A%2018px%3B%0Apadding%3A%205px%205px%3B%0A%7D%0Atable%2C%20table%20th%2C%20table%20td%20%7B%0Aborder%2Dleft%2Dstyle%3A%20none%3B%0Aborder%2Dright%2Dstyle%3A%20none%3B%0A%7D%0Atable%20thead%2C%20table%20tr%2Eeven%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Ap%20%7B%0Amargin%3A%200%2E5em%200%3B%0A%7D%0Ablockquote%20%7B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Apadding%3A%200%2E25em%200%2E75em%3B%0A%7D%0Ahr%20%7B%0Aborder%2Dstyle%3A%20solid%3B%0Aborder%3A%20none%3B%0Aborder%2Dtop%3A%201px%20solid%20%23777%3B%0Amargin%3A%2028px%200%3B%0A%7D%0Adl%20%7B%0Amargin%2Dleft%3A%200%3B%0A%7D%0Adl%20dd%20%7B%0Amargin%2Dbottom%3A%2013px%3B%0Amargin%2Dleft%3A%2013px%3B%0A%7D%0Adl%20dt%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Aul%20%7B%0Amargin%2Dtop%3A%200%3B%0A%7D%0Aul%20li%20%7B%0Alist%2Dstyle%3A%20circle%20outside%3B%0A%7D%0Aul%20ul%20%7B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Apre%2C%20code%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0Aborder%2Dradius%3A%203px%3B%0Acolor%3A%20%23333%3B%0Awhite%2Dspace%3A%20pre%2Dwrap%3B%20%0A%7D%0Apre%20%7B%0Aborder%2Dradius%3A%203px%3B%0Amargin%3A%205px%200px%2010px%200px%3B%0Apadding%3A%2010px%3B%0A%7D%0Apre%3Anot%28%5Bclass%5D%29%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Acode%20%7B%0Afont%2Dfamily%3A%20Consolas%2C%20Monaco%2C%20%27Courier%20New%27%2C%20monospace%3B%0Afont%2Dsize%3A%2085%25%3B%0A%7D%0Ap%20%3E%20code%2C%20li%20%3E%20code%20%7B%0Apadding%3A%202px%200px%3B%0A%7D%0Adiv%2Efigure%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0Aimg%20%7B%0Abackground%2Dcolor%3A%20%23FFFFFF%3B%0Apadding%3A%202px%3B%0Aborder%3A%201px%20solid%20%23DDDDDD%3B%0Aborder%2Dradius%3A%203px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Amargin%3A%200%205px%3B%0A%7D%0Ah1%20%7B%0Amargin%2Dtop%3A%200%3B%0Afont%2Dsize%3A%2035px%3B%0Aline%2Dheight%3A%2040px%3B%0A%7D%0Ah2%20%7B%0Aborder%2Dbottom%3A%204px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Apadding%2Dbottom%3A%202px%3B%0Afont%2Dsize%3A%20145%25%3B%0A%7D%0Ah3%20%7B%0Aborder%2Dbottom%3A%202px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Afont%2Dsize%3A%20120%25%3B%0A%7D%0Ah4%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23f7f7f7%3B%0Amargin%2Dleft%3A%208px%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Ah5%2C%20h6%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23ccc%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Aa%20%7B%0Acolor%3A%20%230033dd%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Aa%3Ahover%20%7B%0Acolor%3A%20%236666ff%3B%20%7D%0Aa%3Avisited%20%7B%0Acolor%3A%20%23800080%3B%20%7D%0Aa%3Avisited%3Ahover%20%7B%0Acolor%3A%20%23BB00BB%3B%20%7D%0Aa%5Bhref%5E%3D%22http%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0Aa%5Bhref%5E%3D%22https%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0A%0Acode%20%3E%20span%2Ekw%20%7B%20color%3A%20%23555%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Edt%20%7B%20color%3A%20%23902000%3B%20%7D%20%0Acode%20%3E%20span%2Edv%20%7B%20color%3A%20%2340a070%3B%20%7D%20%0Acode%20%3E%20span%2Ebn%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Efl%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Ech%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Est%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Eco%20%7B%20color%3A%20%23888888%3B%20font%2Dstyle%3A%20italic%3B%20%7D%20%0Acode%20%3E%20span%2Eot%20%7B%20color%3A%20%23007020%3B%20%7D%20%0Acode%20%3E%20span%2Eal%20%7B%20color%3A%20%23ff0000%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Efu%20%7B%20color%3A%20%23900%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%20%0A" type="text/css" />




</head>

<body>




<h1 class="title toc-ignore">Conceptual Introduction to Dominance Analysis</h1>
<h3 class="subtitle">Examples and Implementation with <code>{domir}</code>’s <code>domin</code></h3>
<h4 class="author">Joseph Luchman</h4>
<h4 class="date">2022-02-19</h4>



<p>The purpose of this vignette is to briefly discuss the conceptual underpinnings of the relative importance method implemented in <code>{domir}</code> and provide several extensive examples that illustrate these concepts as applied to data.</p>
<p>This vignette is intended to serve as a refresher for users familiar with these concepts as well as an brief introduction to them for those who are not.</p>
<p>By the end of this vignette, the reader should have a sense for what the key relative importance method is attempting to do as well as an understanding of how it is accomplished as applied to data.</p>
<div id="conceptual-introduction" class="section level1">
<h1>Conceptual Introduction</h1>
<p>The relative importance method implemented in <code>{domir}</code> produces results that are relatively easy to interpret but is itself a complex method in terms of implementation.</p>
<p>The discussion below outlines what the conceptual origins of the method, what the relative importance method does, and some details about how the DA method is implemented in <code>{domir}</code>.</p>
<div id="dominance-analysis" class="section level2">
<h2>Dominance Analysis</h2>
<p>The focus of the <code>{domir}</code> package is, currently, on dominance analysis (DA). DA can be thought of as an extension of Shapley value decomposition from Cooperative Game Theory (see Grömping, 2007 for a discussion) which seeks to find solutions of how to subdivide payoffs to players in a game based on their relative contribution to the payoff.</p>
<p>This methodology can be applied to predictive modeling in a conceptually straightforward way. Predictive models are, in a sense, a game in which independent variables (IVs)/predictors/features cooperate to produce a payoff in the form of predicting the dependent variable (DV)/outcome/response. The component of the decomposition/the proportion of the payoff ascribed to each IV can then be interpreted as the IVs importance in the context of the model as that is the contribution it makes to predicting the DV.</p>
<p>In application, DA determines the relative importance of IVs in a predictive model based on each IV’s contribution to an overall model fit statistic—a value that describes the entire model’s predictions on a dataset at once. DA’s goal extends beyond just the decomposition of the focal model fit statistic. In fact, DA produces three different results that it uses to compare the contribution each IV makes in the predictive model against the contributions attributed to each other IV. These three results, and their combined use to compare IVs, is the reason DA is an <em>extension of</em> Shapley value decomposition. The three different results are discussed in greater detail in the context of an example discussed below after a brief introduction to the <code>domin</code> function.</p>
</div>
<div id="da-implemtation-with-domirdomin" class="section level2">
<h2>DA Implemtation with <code>domir::domin</code></h2>
<p>The <code>domin</code> function of the <code>{domir}</code> package is an API for applying DA to predictive modeling functions in R. The sections below will use this function to illustrate how DA is implemented and discuss conceptual details of each computation.</p>
<p>Details on how to work with <code>domin</code> in terms of programming and how the API functions are reported on in the <em>domir details</em> vignette.</p>
</div>
</div>
<div id="concepts-in-application" class="section level1">
<h1>Concepts in Application</h1>
<p>The purpose of the <code>{domir}</code> package is to apply DA to predictive models. This section builds on the last by providing an example predictive model with which to illustrate the computation and interpretation of the dominance results produced by DA.</p>
<p>DA was developed originally using linear regression (<code>lm</code>) with the explained variance <span class="math inline">\(R^2\)</span> metric as a fit statistic (Budescu, 1993). The examples below use this model and fit statistic as both are widely used and understood in statistics and data science.</p>
<p>Consider this model using the <em>mtcars</em> data in the <code>{datasets}</code> package.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(datasets)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>lm_cars <span class="ot">&lt;-</span> </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(mpg <span class="sc">~</span> am <span class="sc">+</span> cyl <span class="sc">+</span> carb, <span class="at">data =</span> mtcars)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_cars)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; lm(formula = mpg ~ am + cyl + carb, data = mtcars)</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Residuals:</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; -5.8853 -1.1581  0.2646  1.4885  5.4843 </span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; (Intercept)  32.1731     2.4914  12.914 2.59e-13 ***</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; am            4.2430     1.3094   3.240 0.003074 ** </span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; cyl          -1.7175     0.4298  -3.996 0.000424 ***</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; carb         -1.1304     0.4058  -2.785 0.009481 ** </span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; ---</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Residual standard error: 2.755 on 28 degrees of freedom</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Multiple R-squared:  0.8113, Adjusted R-squared:  0.7911 </span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; F-statistic: 40.13 on 3 and 28 DF,  p-value: 2.855e-10</span></span></code></pre></div>
<p>The results show that all three IVs are statistically significant at the traditional level (i.e., <span class="math inline">\(p &lt; .05\)</span>) and that, in total, the predictors—<em>am, cyl</em>, and <em>carb</em>—explain ~80% of the variance in <em>mpg</em>.</p>
<p>I intend to conduct a DA on this model using <code>domir::domin</code> and implement the DA as follows:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(domir)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">domin</span>(mpg <span class="sc">~</span> am <span class="sc">+</span> cyl <span class="sc">+</span> carb, </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>      lm, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">list</span>(summary, <span class="st">&quot;r.squared&quot;</span>), </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> mtcars)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Overall Fit Statistic:      0.8113023 </span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; General Dominance Statistics:</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;      General Dominance Standardized Ranks</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; am           0.2156848    0.2658501     2</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; cyl          0.4173094    0.5143698     1</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; carb         0.1783081    0.2197801     3</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Conditional Dominance Statistics:</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;         IVs: 1    IVs: 2     IVs: 3</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; am   0.3597989 0.2164938 0.07076149</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; cyl  0.7261800 0.4181185 0.10762967</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; carb 0.3035184 0.1791172 0.05228872</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Complete Dominance Designations:</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              Dmnated?am Dmnated?cyl Dmnated?carb</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dmnates?am           NA       FALSE         TRUE</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dmnates?cyl        TRUE          NA         TRUE</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dmnates?carb      FALSE       FALSE           NA</span></span></code></pre></div>
<p>The <code>domin</code> function above prints out results in four sections:</p>
<ol style="list-style-type: decimal">
<li>fit statistic results</li>
<li>general dominance statistics</li>
<li>conditional dominance statistics</li>
<li>complete dominance designations</li>
</ol>
<p>Below I “replay” and discuss each result in turn.</p>
<div id="fit-statistic-results" class="section level2">
<h2>Fit Statistic Results</h2>
<pre><code>#&gt; Overall Fit Statistic:      0.8113023 </code></pre>
<p>The first result <code>domin</code> prints is related to the overall fit statistic value for the model. In game theory terms, this value is the total payoff all players/IVs produced in the cooperative game/model. Recall that the value reported was</p>
<p>The value produced serves as the fit statistic “to be decomposed” by the DA and is limiting value for how much each IV will be able to explain. The DA will ascribe the three IVs in this model separate components of this ~<span class="math inline">\(.8113\)</span> value related to their contributions to predicting <em>mpg</em>.</p>
<p>Other fit statistic value adjustments are reported in this section as well in particular those associated with the all subsets and constant model adjustments (discussed further below) when used in the DA.</p>
</div>
<div id="general-dominance-statistics" class="section level2">
<h2>General Dominance Statistics</h2>
<pre><code>#&gt; General Dominance Statistics:
#&gt;      General Dominance Standardized Ranks
#&gt; am           0.2156848    0.2658501     2
#&gt; cyl          0.4173094    0.5143698     1
#&gt; carb         0.1783081    0.2197801     3</code></pre>
<p>The second result printed reports the <em>general dominance statistics</em> related to how the overall fit statistic’s value is divided up among the IVs. These also represent the Shapley value decompositions of the fit statistic showing how each player/IV is ascribed a component of the payoff/fit statistic from the game/model.</p>
<p>The <em>General Dominance</em> column of statistics can be interpreted in terms of the fit metric it decomposed. For example, <em>am</em> has a value of ~<span class="math inline">\(0.2157\)</span> which means <em>am</em> is associated with an <span class="math inline">\(R^2\)</span> of about twenty-two percentage points of <em>mpg</em>’s variance given the predictive model and other IVs.</p>
<p>The <em>Standardized</em> column of statistics expresses the general dominance statistic value as a percentage of the overall fit statistic value and thus sum to 100%. <em>am</em>’s contributions to the <span class="math inline">\(R^2\)</span>’s total value is ~27% (i.e., <span class="math inline">\(\frac{.2157}{.8113} = .2659\)</span>).</p>
<p>The final <em>Ranks</em> column is most relevant to the focal purpose of determining the relative importance of the IVs in this model and provides a rank ordering of the IVs based on the general dominance statistics. It is here that DA moves beyond Shapley value decomposition in that DA, and this rank ordering based on general dominance statistics, allows for applying labels to the relationships between IVs in terms of their importance.</p>
<p><em>am</em> is ranked second because it has a smaller general dominance statistic than the first ranked <em>cyl</em>. As such, <em>am</em> “is generally dominated by” <em>cyl</em>. By contrast, <em>am</em> is ranked higher than third ranked <em>carb</em> and thus <em>am</em> “generally dominates” <em>carb</em>. These labels are known as <em>general dominance designations</em>.</p>
<div id="points-of-note-general-dominance" class="section level3">
<h3>Points of Note: General Dominance</h3>
<p>The general dominance statistics always sum to the value of the overall fit statistic and, because they represent parts of a whole, are widely considered the easiest of the dominance statistics to interpret (i.e., as compared to conditional and complete dominance below).</p>
<p>The general dominance statistics, however simple to interpret, are the least stringent of the dominance statistics/designations (reasons why are discussed later). Thus, the requirements to assign the “generally dominates” label to a relationship between two IVs are the easiest to fulfill.</p>
</div>
</div>
<div id="conditional-dominance-statistics" class="section level2">
<h2>Conditional Dominance Statistics</h2>
<pre><code>#&gt; Conditional Dominance Statistics:
#&gt;         IVs: 1    IVs: 2     IVs: 3
#&gt; am   0.3597989 0.2164938 0.07076149
#&gt; cyl  0.7261800 0.4181185 0.10762967
#&gt; carb 0.3035184 0.1791172 0.05228872</code></pre>
<p>The third section reported on by <code>domin</code> prints the <em>conditional dominance statistics</em> associated with each IV. Each IV has a separate conditional statistic related to the number of IVs that are in a sub-model; why this matrix is useful delves into the computation of these statistics which is discussed later. For the time being it suffices to note that, conceptually, these values can be thought of as Shapley values for a specific number of players in the game. Thus, the <em>IVs: 1</em> column reports on the value of the fit statistic/payoff when the IV is “playing alone” (i.e., by itself in the model with no other IVs). Similarly, the <em>IVs: 2</em> column reports on a general value of the fit statistic/payoff when the IV is “playing with one other” (i.e., with another IV irrespective of which) and so on until the column with all IVs in the model (here <em>IVs: 3</em>).</p>
<p>The primary utility of the conditional dominance matrix is that it can be used to designate importance in a way that is more stringent/harder to achieve than the general dominance statistics. Unfortunately, this matrix does not have a ranking like the general dominance statistics and, indeed, it is not necessarily obvious as to how one might use this matrix for determining importance. The way this matrix is used is ‘row-wise’, comparing the results of an entire row/IV against those of another row/IV. If the value of each entry for a row/IV is greater than the value of another row/IV at the same position (i.e., comparing models with the same number of IVs) than an IV is said to “conditionally dominate” another IV. The matrix above shows that <em>am</em> “is conditionally dominated by” <em>cyl</em> as its conditional dominance statistics are smaller than <em>cyl</em>’s at positions 1, 2, and 3. Conversely, <em>am</em> “conditionally dominates” <em>carb</em> as its conditional dominance statistics are greater than <em>carb</em>’s at positions 1, 2, and 3.</p>
<div id="points-of-note-conditional-dominance" class="section level3">
<h3>Points of Note: Conditional Dominance</h3>
<p>Conditional dominance statistics provide more information about each IV than general dominance statistics as they reveal the effect that IV redundancy has on prediction for each IV. To put this a little differently, conditional dominance statistics show more clearly the utility a specific player/IV adds to the payoff/fit metric. As the game/model gets more players/IVs the contribution each can make becomes more limited which is reflected in the trajectory of conditional dominance statistics. The additional information provided, however potentially useful, can be complex to interpret—a problem that grows in magnitude as more IVs are added to the model.</p>
<p>The increase in complexity with conditional dominance over that of general dominance also results in a more stringent set of comparisons. Because the label “conditionally dominates” is only ascribed to a relationship that shows more contribution to the fit metric at all positions of the conditional dominance matrix, it is a more difficult criterion to achieve and is therefore a stronger designation.</p>
<p>Note that conditional dominance implies general dominance–but the reverse is not true. An IV can generally, but not conditionally, dominate another IV.</p>
</div>
</div>
<div id="complete-dominance-designations" class="section level2">
<h2>Complete Dominance Designations</h2>
<pre><code>#&gt; Complete Dominance Designations:
#&gt;              Dmnated?am Dmnated?cyl Dmnated?carb
#&gt; Dmnates?am           NA       FALSE         TRUE
#&gt; Dmnates?cyl        TRUE          NA         TRUE
#&gt; Dmnates?carb      FALSE       FALSE           NA</code></pre>
<p>The fourth section reported on by <code>domin</code> prints the <em>complete dominance designations</em> associated with each IV pair. Each IV is compared to each other IV and has two entries in this matrix. The row labels denote that the IV noted in the label “completely dominates” the IV noted in the column label. By contrast, the column labels denote that the IV in the label “is completely dominated by” the IV in the row label. Each designation is then assigned a logical value or <code>NA</code> (when no such designation can be made given the model results).</p>
<p>The complete dominance designations are useful beyond the general and conditional dominance results as they are the most stringent sets of comparisons. Complete dominance reflects the relative performance of each IV to another IV in all the sub-models where their relative predictive performance can be compared. The results of this section are then not statistics but are an extensive series of inequality comparisons (i.e., in the mathematical sense <span class="math inline">\(&gt;\)</span>, <span class="math inline">\(&lt;\)</span>) of individual sub-models expressed as logical designations.</p>
<div id="points-of-note-complete-dominance" class="section level3">
<h3>Points of Note: Complete Dominance</h3>
<p>Complete dominance designations are the most stringent of the designations as <em>all</em> comparable sub-models for an IV must be larger than its comparison IV for the “conditionally dominates” label to be ascribed to their relationship. The sorts of sub-models that qualify as ‘comparable’ is discussed later.</p>
<p>Also note that complete dominance implies both conditional and general dominance but, again, not the reverse. An IV can conditionally or generally, but not completely, dominate another IV.</p>
</div>
</div>
</div>
<div id="dominance-statistics-and-designations-key-computational-details" class="section level1">
<h1>Dominance Statistics and Designations: Key Computational Details</h1>
<p>The DA methodology currently implemented in <code>{domir}</code> is a relatively assumption-free but computationally expensive methodology that follows from the way Shapley value decomposition was originally formulated.</p>
<p>The sections below begin by providing an analogy for how to think about the computation of DA results, outline exactly how each dominance statistic and designation is determined, as well as extend the example above by applying each computation in the context of the example.</p>
<div id="computational-implementation-da-as-an-experiment" class="section level2">
<h2>Computational Implementation: DA as an Experiment</h2>
<p>Shapley value decomposition and DA have traditionally been implemented by treating the cooperative game/predictive model as though it was an experimental design which seeks to evaluate the impact of the players/IVs on the payoff/fit statistic. When designing the experiment applied to the model, it is assumed that the only factors are the IVs and that they all have two levels: 1) the IV is included in the sub-model or 2) the IV is excluded from the sub-model—all other potential inputs to the model are constant.</p>
<p>The specific type of design applied to the model is a full-factorial design where all possible combinations of the IVs included or excluded are estimated as sub-models. When there are <span class="math inline">\(p\)</span> IVs in the model there will be <span class="math inline">\(2^p\)</span> sub-models estimated. The full-factorial design required for computing dominance statistics and designations is why the traditional approach is considered computationally expensive—each additional IV added to the model results in a geometric increase in the number of requires sub-models to estimate.</p>
</div>
<div id="da-results-the-full-factorial-design" class="section level2">
<h2>DA Results: The Full-Factorial Design</h2>
<p>The DA results related to the <code>lm</code> model with three IVs discussed above is composed of 8 sub-models and their <span class="math inline">\(R^2\)</span> values. The <code>domin</code> function, if supplied a predictive modeling function that can record each sub-model’s results, can be adapted to capture each sub-model’s <span class="math inline">\(R^2\)</span> value along with the IVs that comprise it.</p>
<p>The code below constructs a wrapper function to export results from each sub-model to an external data frame. The code to produce these results is complex and each line is commented to note its purpose. This wrapper function then replaces <code>lm</code> in the call to <code>domin</code> so that, as the DA is executed, all the sub-models’ data are captured for the illustration to come.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>lm_capture <span class="ot">&lt;-</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(formula, ...) { <span class="co"># wrapper program that accepts formula and ellipsis arguments</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    count <span class="ot">&lt;&lt;-</span> count <span class="sc">+</span> <span class="dv">1</span> <span class="co"># increment counter in enclosing environment</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    lm_obj <span class="ot">&lt;-</span> <span class="fu">lm</span>(formula, ...) <span class="co"># estimate &#39;lm&#39; model and save object</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    DA_results[count, <span class="st">&quot;formula&quot;</span>] <span class="ot">&lt;&lt;-</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">deparse</span>(formula) <span class="co"># record string version of formula passed in &#39;DA_results&#39; in enclosing environment</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    DA_results[count, <span class="st">&quot;R^2&quot;</span>] <span class="ot">&lt;&lt;-</span> </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">summary</span>(lm_obj)[[<span class="st">&quot;r.squared&quot;</span>]] <span class="co"># record R^2 in &#39;DA_results&#39; in enclosing environment</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(lm_obj) <span class="co"># return &#39;lm&#39; class-ed object</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>count <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="co"># initialize the count indicating the row in which the results will fill-in</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>DA_results <span class="ot">&lt;-</span> <span class="co"># container data frame in which to record results</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">formula =</span> <span class="fu">rep</span>(<span class="st">&quot;&quot;</span>, <span class="at">times =</span> <span class="dv">2</span><span class="sc">^</span><span class="dv">3-1</span>), </span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>             <span class="st">`</span><span class="at">R^2</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="at">times =</span> <span class="dv">2</span><span class="sc">^</span><span class="dv">3-1</span>), </span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">check.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>lm_da <span class="ot">&lt;-</span> <span class="fu">domin</span>(mpg <span class="sc">~</span> am <span class="sc">+</span> cyl <span class="sc">+</span> carb, <span class="co"># implement the DA with the wrapper</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>               lm_capture, </span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>               <span class="fu">list</span>(summary, <span class="st">&quot;r.squared&quot;</span>), </span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> mtcars)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>DA_results</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                 formula       R^2</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1              mpg ~ am 0.3597989</span></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2             mpg ~ cyl 0.7261800</span></span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3        mpg ~ am + cyl 0.7590135</span></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4            mpg ~ carb 0.3035184</span></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5       mpg ~ am + carb 0.7036726</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6      mpg ~ cyl + carb 0.7405408</span></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7 mpg ~ am + cyl + carb 0.8113023</span></span></code></pre></div>
<p>The printed result from the <em>DA_results</em> container data frame shows that <code>domin</code> runs 7 sub-models; each a different combination of the IVs. Note that, by default, the sub-model where all IVs are excluded is assumed to result in a fit statistic value of 0 and is not estimated directly (which can be changed with the <code>consmodel</code> argument).</p>
<p>The <span class="math inline">\(R^2\)</span> values recorded in <em>DA_results</em> are used to compute the dominance statistics and designations reported on above.</p>
<div id="complete-dominance-designations-1" class="section level3">
<h3>Complete Dominance Designations</h3>
<p>Complete dominance between two IVs is designated by:</p>
<p><span class="math display">\[X_vDX_z\; if\;2^{p-2}\, =\, \Sigma^{2^{p-2}}_{j=1}{ \{\begin{matrix} if\, F_{X_v\; \cup\;S_j}\, &gt; F_{X_z\; \cup\;S_j}\, \,then\, 1\, \\ if\, F_{X_v\; \cup\;S_j}\, \le F_{X_z\; \cup\;S_j}\,then\, \,0\end{matrix} }\]</span></p>
<p>Where <span class="math inline">\(X_v\)</span> and <span class="math inline">\(X_z\)</span> are two IVs, <span class="math inline">\(S_j\)</span> is a distinct set of the other IVs in the model not including <span class="math inline">\(X_v\)</span> and <span class="math inline">\(X_z\)</span> which can include the null set (<span class="math inline">\(\emptyset\)</span>) with no other IVs, and <span class="math inline">\(F\)</span> is a model fit statistic. Conceptually, this computation implies that when <strong>all</strong> <span class="math inline">\(2^{p-2}\)</span> comparisons show that <span class="math inline">\(X_v\)</span> is greater than <span class="math inline">\(X_z\)</span>, then <span class="math inline">\(X_v\)</span> completely dominates <span class="math inline">\(X_z\)</span>.</p>
<p>The results from <em>DA_results</em> can then be used to make the comparisons required to determine whether each pair of IVs completely dominates the other. The comparison begins with the results for <code>am</code> and <code>cyl</code>.</p>
<table>
<caption>Complete Dominance Comparisons: <code>am</code> versus <code>cyl</code></caption>
<thead>
<tr class="header">
<th align="left">formula</th>
<th align="right">R^2</th>
<th align="left">formula</th>
<th align="right">R^2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg ~ am</td>
<td align="right">0.360</td>
<td align="left">mpg ~ cyl</td>
<td align="right">0.726</td>
</tr>
<tr class="even">
<td align="left">mpg ~ am + carb</td>
<td align="right">0.704</td>
<td align="left">mpg ~ cyl + carb</td>
<td align="right">0.741</td>
</tr>
</tbody>
</table>
<p>The rows in the table above are aligned such that comparable models are in the rows. As applied to this example, the <span class="math inline">\(S_j\)</span> sets are <span class="math inline">\(\emptyset\)</span> with no other IVs and the set also including <em>carb</em>.</p>
<p>The <span class="math inline">\(R^2\)</span> values across the comparable models show that <em>cyl</em> clearly has larger <span class="math inline">\(R^2\)</span> values than <em>am</em>.</p>
<table>
<caption>Complete Dominance Comparisons: <code>am</code> versus <code>carb</code></caption>
<thead>
<tr class="header">
<th align="left">formula</th>
<th align="right">R^2</th>
<th align="left">formula</th>
<th align="right">R^2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg ~ am</td>
<td align="right">0.360</td>
<td align="left">mpg ~ carb</td>
<td align="right">0.304</td>
</tr>
<tr class="even">
<td align="left">mpg ~ am + cyl</td>
<td align="right">0.759</td>
<td align="left">mpg ~ cyl + carb</td>
<td align="right">0.741</td>
</tr>
</tbody>
</table>
<p>Here the <span class="math inline">\(S_j\)</span> sets are, again, <span class="math inline">\(\emptyset\)</span> and the set also including <em>cyl</em>.</p>
<p>The <span class="math inline">\(R^2\)</span> values across the comparable models show that <em>am</em> has larger <span class="math inline">\(R^2\)</span> values than <em>carb</em>.</p>
<table>
<caption>Complete Dominance Comparisons: <code>cyl</code> versus <code>carb</code></caption>
<thead>
<tr class="header">
<th align="left">formula</th>
<th align="right">R^2</th>
<th align="left">formula</th>
<th align="right">R^2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg ~ cyl</td>
<td align="right">0.726</td>
<td align="left">mpg ~ carb</td>
<td align="right">0.304</td>
</tr>
<tr class="even">
<td align="left">mpg ~ am + cyl</td>
<td align="right">0.759</td>
<td align="left">mpg ~ am + carb</td>
<td align="right">0.704</td>
</tr>
</tbody>
</table>
<p>Finally, the <span class="math inline">\(S_j\)</span> sets are the <span class="math inline">\(\emptyset\)</span> and the set also including <em>am</em>.</p>
<p>The <span class="math inline">\(R^2\)</span> values across the comparable models show that <em>cyl</em> has larger <span class="math inline">\(R^2\)</span> values than <em>carb</em>.</p>
<p>Each of these three sets of comparisons are represented in the <em>Complete_Dominance</em> matrix.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>lm_da<span class="sc">$</span>Complete_Dominance</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              Dmnated_am Dmnated_cyl Dmnated_carb</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dmnates_am           NA       FALSE         TRUE</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dmnates_cyl        TRUE          NA         TRUE</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dmnates_carb      FALSE       FALSE           NA</span></span></code></pre></div>
</div>
<div id="computing-conditional-dominance" class="section level3">
<h3>Computing Conditional Dominance</h3>
<p>Conditional dominance statistics are computed as:</p>
<p><span class="math display">\[C^i_{X_v} = \Sigma^{\begin{bmatrix}p-1\\i-1\end{bmatrix}}_{i=1}{\frac{F_{X_v\; \cup\; S_i}\, - F_{S_i}}{\begin{bmatrix}p-1\\i-1\end{bmatrix}}}\]</span></p>
<p>Where <span class="math inline">\(S_i\)</span> is a subset of IVs not including <span class="math inline">\(X_v\)</span> and <span class="math inline">\(\begin{bmatrix}p-1\\i-1\end{bmatrix}\)</span> is the number of distinct combinations produced choosing the number of elements in the bottom value (<span class="math inline">\(i-1\)</span>) given the number of elements in the top value (<span class="math inline">\(p-1\)</span>; i.e., the value produced by <code>choose(p-1, i-1)</code>).</p>
<p>In effect, the formula above amounts to an average of the differences between each model containing <span class="math inline">\(X_v\)</span> from the comparable model not containing it by the number of IVs in the model total. As applied to the results from <em>DA_results</em>, <em>am</em>’s conditional dominance statistics are computed with the following differences:</p>
<table>
<caption>Conditional Dominance Computations: <code>am</code> with One IV/Alone</caption>
<thead>
<tr class="header">
<th align="left">formula minutend</th>
<th align="right">R^2 minutend</th>
<th align="left">formula subtrahend</th>
<th align="right">R^2 subtrahend</th>
<th align="right">difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg ~ am</td>
<td align="right">0.36</td>
<td align="left">mpg ~ 1</td>
<td align="right">0</td>
<td align="right">0.36</td>
</tr>
</tbody>
</table>
<table>
<caption>Conditional Dominance Computations: <code>am</code> with Two IVs</caption>
<thead>
<tr class="header">
<th align="left">formula minutend</th>
<th align="right">R^2 minutend</th>
<th align="left">formula subtrahend</th>
<th align="right">R^2 subtrahend</th>
<th align="right">difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg ~ am + cyl</td>
<td align="right">0.759</td>
<td align="left">mpg ~ cyl</td>
<td align="right">0.726</td>
<td align="right">0.033</td>
</tr>
<tr class="even">
<td align="left">mpg ~ am + carb</td>
<td align="right">0.704</td>
<td align="left">mpg ~ carb</td>
<td align="right">0.304</td>
<td align="right">0.400</td>
</tr>
</tbody>
</table>
<table>
<caption>Conditional Dominance Computations: <code>am</code> with Three IVs/Full Model</caption>
<thead>
<tr class="header">
<th align="left">formula minutend</th>
<th align="right">R^2 minutend</th>
<th align="left">formula subtrahend</th>
<th align="right">R^2 subtrahend</th>
<th align="right">difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg ~ am + cyl + carb</td>
<td align="right">0.811</td>
<td align="left">mpg ~ cyl + carb</td>
<td align="right">0.741</td>
<td align="right">0.071</td>
</tr>
</tbody>
</table>
<p>The rows of each table represent a difference to be recorded for the conditional dominance statistics computation. In the one, two, and three IV comparison tables, the model with <em>am</em> is presented first (as the minutend) and the comparable model without <em>am</em> is presented second (as the subtrahend)—for the 1 IV comparison table, this model is the intercept only model that, as is noted above, is assumed to have a value of 0. The difference is presented last.</p>
<p>By table, the differences are averaged resulting in the 0.36 value at one IV, the 0.216 at two IVs, and 0.071 at three IVs.</p>
<p>Next the computations for <em>cyl</em> are reported.</p>
<table>
<caption>Conditional Dominance Computations: <code>cyl</code> with One IV/Alone</caption>
<thead>
<tr class="header">
<th align="left">formula minutend</th>
<th align="right">R^2 minutend</th>
<th align="left">formula subtrahend</th>
<th align="right">R^2 subtrahend</th>
<th align="right">difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg ~ cyl</td>
<td align="right">0.726</td>
<td align="left">mpg ~ 1</td>
<td align="right">0</td>
<td align="right">0.726</td>
</tr>
</tbody>
</table>
<table>
<caption>Conditional Dominance Computations: <code>cyl</code> with Two IVs</caption>
<thead>
<tr class="header">
<th align="left">formula minutend</th>
<th align="right">R^2 minutend</th>
<th align="left">formula subtrahend</th>
<th align="right">R^2 subtrahend</th>
<th align="right">difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg ~ am + cyl</td>
<td align="right">0.759</td>
<td align="left">mpg ~ am</td>
<td align="right">0.360</td>
<td align="right">0.399</td>
</tr>
<tr class="even">
<td align="left">mpg ~ cyl + carb</td>
<td align="right">0.741</td>
<td align="left">mpg ~ carb</td>
<td align="right">0.304</td>
<td align="right">0.437</td>
</tr>
</tbody>
</table>
<table>
<caption>Conditional Dominance Computations: <code>cyl</code> with Three IVs/Full Model</caption>
<thead>
<tr class="header">
<th align="left">formula minutend</th>
<th align="right">R^2 minutend</th>
<th align="left">formula subtrahend</th>
<th align="right">R^2 subtrahend</th>
<th align="right">difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg ~ am + cyl + carb</td>
<td align="right">0.811</td>
<td align="left">mpg ~ am + carb</td>
<td align="right">0.704</td>
<td align="right">0.108</td>
</tr>
</tbody>
</table>
<p>Again, the differences are averaged resulting in the 0.726 value at one IV, the 0.418 at two IVs, and 0.108 at three IVs.</p>
<p>Finally, the computations for <em>carb</em>.</p>
<table>
<caption>Conditional Dominance Computations: <code>carb</code> with One IV/Alone</caption>
<thead>
<tr class="header">
<th align="left">formula minutend</th>
<th align="right">R^2 minutend</th>
<th align="left">formula subtrahend</th>
<th align="right">R^2 subtrahend</th>
<th align="right">difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg ~ carb</td>
<td align="right">0.304</td>
<td align="left">mpg ~ 1</td>
<td align="right">0</td>
<td align="right">0.304</td>
</tr>
</tbody>
</table>
<table>
<caption>Conditional Dominance Computations: <code>carb</code> with Two IVs</caption>
<thead>
<tr class="header">
<th align="left">formula minutend</th>
<th align="right">R^2 minutend</th>
<th align="left">formula subtrahend</th>
<th align="right">R^2 subtrahend</th>
<th align="right">difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg ~ am + carb</td>
<td align="right">0.704</td>
<td align="left">mpg ~ am</td>
<td align="right">0.360</td>
<td align="right">0.344</td>
</tr>
<tr class="even">
<td align="left">mpg ~ cyl + carb</td>
<td align="right">0.741</td>
<td align="left">mpg ~ cyl</td>
<td align="right">0.726</td>
<td align="right">0.014</td>
</tr>
</tbody>
</table>
<table>
<caption>Conditional Dominance Computations: <code>carb</code> with Three IVs/Full Model</caption>
<thead>
<tr class="header">
<th align="left">formula minutend</th>
<th align="right">R^2 minutend</th>
<th align="left">formula subtrahend</th>
<th align="right">R^2 subtrahend</th>
<th align="right">difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg ~ am + cyl + carb</td>
<td align="right">0.811</td>
<td align="left">mpg ~ am + cyl</td>
<td align="right">0.759</td>
<td align="right">0.052</td>
</tr>
</tbody>
</table>
<p>And again, the differences are averaged resulting in the 0.304 value at one IV, the 0.179 at two IVs, and 0.052 at three IVs.</p>
<p>These nine values then populate the conditional dominance statistic matrix.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>lm_da<span class="sc">$</span>Conditional_Dominance</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;          IVs_1     IVs_2      IVs_3</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; am   0.3597989 0.2164938 0.07076149</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; cyl  0.7261800 0.4181185 0.10762967</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; carb 0.3035184 0.1791172 0.05228872</span></span></code></pre></div>
<p>The conditional dominance matrix’s values can then be used in a way similar to the complete dominance designations above in creating a series of logical designations indicating whether each IV conditionally dominates each other.</p>
<p>Below the comparisons begin with <em>am</em> and <em>cyl</em></p>
<table>
<caption>Conditional Dominance Designation: <code>am</code> Compared to <code>cyl</code></caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">am</th>
<th align="right">cyl</th>
<th align="left">comparison</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">IVs_1</td>
<td align="right">0.360</td>
<td align="right">0.726</td>
<td align="left">FALSE</td>
</tr>
<tr class="even">
<td align="left">IVs_2</td>
<td align="right">0.216</td>
<td align="right">0.418</td>
<td align="left">FALSE</td>
</tr>
<tr class="odd">
<td align="left">IVs_3</td>
<td align="right">0.071</td>
<td align="right">0.108</td>
<td align="left">FALSE</td>
</tr>
</tbody>
</table>
<p>The table above is a transpose of the conditional dominance statistic matrix with an additional <em>comparison</em> column indicating whether the first IV/<em>am</em>’s conditional dominance statistic at that number of IVs is greater than the second IV/<em>cyl</em>’s.</p>
<p>Conditional dominance is determined by all values being <code>TRUE</code> or <code>FALSE</code>; in this case, <em>cyl</em> is seen to conditionally dominate <em>am</em> as all values are <code>FALSE</code>.</p>
<p>Next is the comparison between <em>am</em> and <em>carb</em></p>
<table>
<caption>Conditional Dominance Designation: <code>am</code> Compared to <code>carb</code></caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">am</th>
<th align="right">carb</th>
<th align="left">comparison</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">IVs_1</td>
<td align="right">0.360</td>
<td align="right">0.304</td>
<td align="left">TRUE</td>
</tr>
<tr class="even">
<td align="left">IVs_2</td>
<td align="right">0.216</td>
<td align="right">0.179</td>
<td align="left">TRUE</td>
</tr>
<tr class="odd">
<td align="left">IVs_3</td>
<td align="right">0.071</td>
<td align="right">0.052</td>
<td align="left">TRUE</td>
</tr>
</tbody>
</table>
<p>Here <em>am</em> conditionally dominates <em>carb</em> as all values are <code>TRUE</code>.</p>
<p>The final comparison between <em>cyl</em> and <em>carb</em></p>
<table>
<caption>Conditional Dominance Designation: <code>cyl</code> Compared to <code>carb</code></caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">cyl</th>
<th align="right">carb</th>
<th align="left">comparison</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">IVs_1</td>
<td align="right">0.726</td>
<td align="right">0.304</td>
<td align="left">TRUE</td>
</tr>
<tr class="even">
<td align="left">IVs_2</td>
<td align="right">0.418</td>
<td align="right">0.179</td>
<td align="left">TRUE</td>
</tr>
<tr class="odd">
<td align="left">IVs_3</td>
<td align="right">0.108</td>
<td align="right">0.052</td>
<td align="left">TRUE</td>
</tr>
</tbody>
</table>
<p><em>cyl</em> also conditionally dominates <em>carb</em> as all values are <code>TRUE</code>.</p>
<p>As was mentioned in the <strong>Concepts in Application</strong> section, because we knew all three IVs have complete dominance designations relative to one another, they necessarily also had conditional dominance designations relative to one another.</p>
</div>
<div id="computing-general-dominance" class="section level3">
<h3>Computing General Dominance</h3>
<p>General dominance is computed as:</p>
<p><span class="math display">\[C_{X_v} = \Sigma^p_{i=1}{\frac{C^i_{X_v}}{p}}\]</span></p>
<p>Where, <span class="math inline">\(C^{i}_{X_x}\)</span> are the conditional dominance statistics for <span class="math inline">\(X_v\)</span> with <span class="math inline">\(i\)</span> IVs. Hence, the general dominance statistics are the arithmetic average of all the conditional dominance statistics for an IV.</p>
<p>When applied to <em>am</em>’s results, the general dominance statistic value is:</p>
<table>
<caption>General Dominance Computations: <code>am</code></caption>
<thead>
<tr class="header">
<th align="right">IVs_1</th>
<th align="right">IVs_2</th>
<th align="right">IVs_3</th>
<th align="right">general dominance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.36</td>
<td align="right">0.216</td>
<td align="right">0.071</td>
<td align="right">0.216</td>
</tr>
</tbody>
</table>
<p>Next to <em>cyl</em>.</p>
<table>
<caption>General Dominance Computations: <code>cyl</code></caption>
<thead>
<tr class="header">
<th align="right">IVs_1</th>
<th align="right">IVs_2</th>
<th align="right">IVs_3</th>
<th align="right">general dominance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.726</td>
<td align="right">0.418</td>
<td align="right">0.108</td>
<td align="right">0.417</td>
</tr>
</tbody>
</table>
<p>And lastly <em>carb</em>.</p>
<table>
<caption>General Dominance Computations: <code>carb</code></caption>
<thead>
<tr class="header">
<th align="right">IVs_1</th>
<th align="right">IVs_2</th>
<th align="right">IVs_3</th>
<th align="right">general dominance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.304</td>
<td align="right">0.179</td>
<td align="right">0.052</td>
<td align="right">0.178</td>
</tr>
</tbody>
</table>
<p>Taken as a set, these values represent the general dominance statistic/Shapley value decomposition vector:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>lm_da<span class="sc">$</span>General_Dominance</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;        am       cyl      carb </span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 0.2156848 0.4173094 0.1783081</span></span></code></pre></div>
<p>The general dominance statistic vector can also be used in a way similar to that of the complete and conditional dominance designations by ranking each value.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(<span class="at">IV =</span> <span class="fu">names</span>(lm_da<span class="sc">$</span>General_Dominance), <span class="st">`</span><span class="at">general dominance</span><span class="st">`</span> <span class="ot">=</span> lm_da<span class="sc">$</span>General_Dominance, <span class="at">ranks =</span> lm_da<span class="sc">$</span>Ranks, <span class="at">check.names =</span> <span class="cn">FALSE</span>), <span class="at">row.names =</span> <span class="cn">FALSE</span>, <span class="at">caption =</span> <span class="st">&quot;General Dominance Designations&quot;</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<table>
<caption>General Dominance Designations</caption>
<thead>
<tr class="header">
<th align="left">IV</th>
<th align="right">general dominance</th>
<th align="right">ranks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">am</td>
<td align="right">0.216</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left">cyl</td>
<td align="right">0.417</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">carb</td>
<td align="right">0.178</td>
<td align="right">3</td>
</tr>
</tbody>
</table>
<p>The rank ordering above shows that <em>am</em> is generally dominated by <em>cyl</em>, <em>am</em> generally dominates <em>carb</em>, and <em>cyl</em> also generally dominates <em>carb</em>.</p>
<p>Again because we knew all three IVs have complete and conditional dominance designations relative to one another, they necessarily also had general dominance designations relative to one another.</p>
<div id="general-dominanceshapley-values-weighted-average-of-all-submodels" class="section level4">
<h4>General Dominance/Shapley Values: Weighted Average of All Submodels</h4>
<p>It is also worth pointing out a subtle feature of the general dominance statistics that tends to be more explicit in the Shapley value decomposition literature, that each general dominance statistic is a weighted average of <strong>all</strong> <span class="math inline">\(2^p\)</span> fit statistics.</p>
<p>To see how this is the case, first recall the computations related to obtaining conditional dominance statistics for the <em>am</em> IV. If you look at all the entries in the three tables, all 8 models are included either as a minutend or a subtrahend. The general dominance statistics are then just an average of these three conditional dominance statistics. Hence, the general dominance statistics include the value for <strong>every</strong> model.</p>
<p>The conditional dominance statistics for <em>cyl</em> and <em>carb</em> re-arrange these same models but otherwise use the same information to produce their general dominance statistics.</p>
</div>
</div>
</div>
<div id="strongest-dominance-designations" class="section level2">
<h2>Strongest Dominance Designations</h2>
<p>Whereas all dominance designations have been made in the example above, the strongest designation between two IVs is likely of primary interest as the strongest designation, as is noted above, implies all weaker designations.</p>
<p>To access the strongest dominance designations, the DA object can be submitted to the <code>summary</code> function.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_da)<span class="sc">$</span>Strongest_Dominance</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                                                                            </span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  &quot;am&quot;                         &quot;am&quot;                   &quot;cyl&quot;                 </span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  &quot;is completely dominated by&quot; &quot;completely dominates&quot; &quot;completely dominates&quot;</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  &quot;cyl&quot;                        &quot;carb&quot;                 &quot;carb&quot;</span></span></code></pre></div>
<p>The result the <code>summary</code> function produces in the <em>Strongest_Dominance</em> element is consistent with expectation in that all three IV interrelationships have complete dominance designations between them.</p>
</div>
</div>
<div id="parting-thoughts-key-caveat" class="section level1">
<h1>Parting Thoughts: Key Caveat</h1>
<p>The DA method implemented by the <code>domir::domin</code> function makes assumptions about the nature of the model that is dominance analyzed; in particular, that the predictive model used in it is “pre-selected”. Hence, the model has been passed through model selection procedures and the user is confident that the IVs/players in the model/game and are, in fact, reasonable to include. DA is intended for use as a model selection tool.</p>
<p>“Relative importance” as a concept is used in many different ways in statistics and data science and many of them refer to methods that are focused on, or are probably best used for, model selection/identifying trivial IVs for removal. DA is a method that is more focused on importance in a “model evaluation” sense. I see this as being an application where the user describes/interprets IVs’ effects in the context of a finalized, predictive approach.</p>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
